spring:
  application:
    name: moodiary-back

  datasource:
    url: jdbc:mysql://localhost:3306/diarydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: moodiary_developer
    password: "diary723!"

  jwt:
    secret: vmfdfdddoiioueioidohfdbfndbfbdbfbwbqbqqooodididdaapwkqqqqqqqqqqqqq
